config/routes.rb
Rails.application.routes.draw do

  resources :cocktails do
    resources :doses, only: [:create]
  end
  resources :doses, only:[:destroy]

  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attachments :photos, maximum: 2
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail_id, uniqueness: { scope: :ingredient_id}

  def unity(unity="")
    @unity = unity
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @dose = Dose.new
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :description, photos: [])
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.description = @dose.description + params[:dose][:unity]
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.input :photos, as: :attachinary %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="container">
   <h1>Lists of Cocktails</h1>
     <h3>Cocktails :</h3>
      <% @cocktails.each do |cocktail| %>

        <div class="row">
          <h4><%= cocktail.name %></h4>
          <span><%= link_to 'Show', cocktail , {class: "btn btn-primary btn-lg active"}%></span>

          <span><%= link_to 'Edit', edit_cocktail_path(cocktail), {class: "btn btn-success btn-lg active"} %></span>

          <button type="button" class="btn btn-danger btn-lg active"><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>
      <% end %>
    </div>




<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<ul>
<% @cocktail.doses.each do |dose|%>
<li>
  <%= dose.description %> | <%= dose.ingredient.name %> | <%= link_to "destroy", dose_path(dose), method: :delete %>
</li>
<% end %>
</ul>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.select :unity, collection: %w(gr. cl. l.) %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>

     <% @cocktail.photos.each do |photo| %>
      <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
    <% end %>

      <%= f.submit %>
<% end %>


<br>
<%= link_to 'Return to Home', cocktails_path, {class: "btn btn-default"} %>

app/views/dose/create.html.erb
<h1>Dose#create</h1>
<p>Find me in app/views/dose/create.html.erb</p>

app/views/dose/destroy.html.erb
<h1>Dose#destroy</h1>
<p>Find me in app/views/dose/destroy.html.erb</p>

app/views/dose/index.html.erb
<h1>Dose#index</h1>
<p>Find me in app/views/dose/index.html.erb</p>

app/views/dose/new.html.erb
<h1>Dose#new</h1>
<p>Find me in app/views/dose/new.html.erb</p>

app/views/ingredient/destroy.html.erb
<h1>Ingredient#destroy</h1>
<p>Find me in app/views/ingredient/destroy.html.erb</p>

app/views/ingredient/index.html.erb
<h1>Ingredient#index</h1>
<p>Find me in app/views/ingredient/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="share-links">
  <a href="#" class="share-link bg-facebook">
    <i class="fa fa-facebook"></i>
  </a>
  <a href="#" class="share-link bg-twitter">
    <i class="fa fa-twitter"></i>
  </a>
  <a href="#" class="share-link bg-email">
    <i class="fa fa-envelope-o"></i>
  </a>
  <a href="#" class="share-link bg-text">
    <i class="fa fa-mobile"></i>
  </a>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://karr.lewagon.org/assets/logo-b44a1618b209b4ad0fdaf489bcde8be64300ea6da3bec54e54ec0df83e2b7cff.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>